services:
  manifest-viewer-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: manifest-viewer-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8081:80
    environment:
      - NODE_ENV=development
